language: php

php:
  - 7.1

sudo: true

addons:
  apt:
    packages:
      - nginx
  hosts:
    - dec-drupal.local

mysql:
  database: dec_drupal
  username: root
  encoding: utf8

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'xdebug.max_nesting_level = 512' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer --verbose self-update
  - composer global require "hirak/prestissimo:^0.3"

install:
  - composer --verbose install

before_script:
  - cp $TRAVIS_BUILD_DIR/config/travis.settings.php $TRAVIS_BUILD_DIR/config/local.settings.php
  - cd $TRAVIS_BUILD_DIR/web
  - $TRAVIS_BUILD_DIR/vendor/bin/drush site-install config_installer --account-name=admin --account-pass=admin --site-name="DEC Drupal" --yes

  # Start web server.
  - $TRAVIS_BUILD_DIR/vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3

  # Nginx
  - sudo cp $TRAVIS_BUILD_DIR/config/travis_nginx.conf /etc/nginx/nginx.conf
  - sudo /etc/init.d/nginx restart

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://127.0.0.1:8080

  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/dec_drupal

script:
  # Code coverage.
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p $TRAVIS_BUILD_DIR/build/logs
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/phpunit.xml.dist
